version: '3.8'
services:
  users-api:
    container_name: users-api-container
    build: .
    ports:
      - "3000:4111"
    env_file: 
          - .env
    depends_on:
      - database

  database:
    container_name: database-container
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: