version: '3.8'
services:
  api:
    container_name: api
    build: .
    ports:
      - "4111:4111"
    env_file: 
      - .env
    environment:
      - PORT=4111
      - MONGO_DB_URL=mongodb://database:27017/users-db
    depends_on:
      - database

  database:
    container_name: database
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: